version: '3.8'

services:
    # ─── PHP / Laravel ────────────────────────────────────────────────
    app:
        build:
            context: .
        image: laravel-vue-ecom_app
        container_name: app
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            - db
        volumes:
            - ./:/var/www/html:delegated
            - node_modules:/var/www/html/node_modules
        ports:
            - "9000:9000"

    # ─── Nginx front‑end proxy ────────────────────────────────────────
    web:
        image: nginx:stable-alpine
        container_name: web
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        depends_on:
            - app

    # ─── MySQL database ────────────────────────────────────────────────
    db:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE:  laravel
            MYSQL_USER:      laravel
            MYSQL_PASSWORD:  secret
        volumes:
            - dbdata:/var/lib/mysql

    # ─── MailHog (SMTP + web UI) ───────────────────────────────────────
    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        restart: unless-stopped
        ports:
            - "1025:1025"
            - "8025:8025"

    # ─── Vite Dev Server for Vue Admin ─────────────────────────────────
    frontend:
        image: node:18-alpine
        container_name: vite_dev
        working_dir: /var/www/html/backend
        volumes:
            - ./:/var/www/html:delegated
            - frontend_node_modules:/var/www/html/backend/node_modules
        ports:
            - "3000:3000"
        environment:
            CHOKIDAR_USEPOLLING: "true"
        command: >
            sh -c "npm ci &&
                   npm run dev -- --host 0.0.0.0 --port 3000"
        depends_on:
            - app

volumes:
    dbdata:
    node_modules:
    frontend_node_modules:
